when:
  branch: main
  event: [push, manual]

steps:
  - name: deploy
    image: alpine
    commands:
      - mkdir -p /sites/root
      - rm -rf /sites/root/*
      - cp -r ./* /sites/root/
    volumes:
      - /srv/sites/:/sites
