when:
  branch: main
  event: [push, manual]

steps:
  - name: deploy
    image: alpine
    commands:
      - mkdir -p /sites/public
      - rm -rf /sites/public/*
      - cp -r ./* /sites/public/
    volumes:
      - /srv/sites/:/sites
